"""empty message

Revision ID: 092d9a6968f8
Revises: cbb357afe4e7
Create Date: 2021-10-02 16:16:06.996841

"""
from alembic import op
import sqlalchemy as sa
import ormar.fields.sqlalchemy_uuid


# revision identifiers, used by Alembic.
revision = '092d9a6968f8'
down_revision = 'cbb357afe4e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apartments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('apartments_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', ormar.fields.sqlalchemy_uuid.CHAR(36), nullable=True),
    sa.Column('apartment', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['apartment'], ['apartments.id'], name='fk_apartments_users_apartments_apartment_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user'], ['users.id'], name='fk_apartments_users_users_user_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('apartment', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['apartment'], ['apartments.id'], name='fk_rooms_apartments_id_apartment', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rooms')
    op.drop_table('apartments_users')
    op.drop_table('apartments')
    # ### end Alembic commands ###
