"""empty message

Revision ID: 1e1c9d7bcc4b
Revises: c5bf7b8081ad
Create Date: 2021-10-15 20:46:29.108847

"""
from alembic import op
import sqlalchemy as sa
import ormar.fields.sqlalchemy_uuid
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "1e1c9d7bcc4b"
down_revision = "c5bf7b8081ad"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "taskschedules_users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user", ormar.fields.sqlalchemy_uuid.CHAR(36), nullable=True),
        sa.Column("taskschedule", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["taskschedule"],
            ["task_sheldules.id"],
            name="fk_taskschedules_users_task_sheldules_taskschedule_id",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user"],
            ["users.id"],
            name="fk_taskschedules_users_users_user_id",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "completedtasks_users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user", ormar.fields.sqlalchemy_uuid.CHAR(36), nullable=True),
        sa.Column("completedtask", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["completedtask"],
            ["completed_tasks.id"],
            name="fk_completedtasks_users_completed_tasks_completedtask_id",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user"],
            ["users.id"],
            name="fk_completedtasks_users_users_user_id",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "completed_tasks", sa.Column("scheduled_task", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        "fk_completed_tasks_shelduled_tasks_id_scheduled_task",
        "completed_tasks",
        "shelduled_tasks",
        ["scheduled_task"],
        ["id"],
    )
    op.add_column(
        "shelduled_tasks", sa.Column("task_schedule", sa.Integer(), nullable=True)
    )
    op.add_column(
        "shelduled_tasks",
        sa.Column("scheduled_to", sa.DateTime(timezone=True), nullable=False),
    )
    op.drop_constraint(
        "fk_shelduled_tasks_task_sheldules_id_task_sheldule",
        "shelduled_tasks",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_shelduled_tasks_task_sheldules_id_task_schedule",
        "shelduled_tasks",
        "task_sheldules",
        ["task_schedule"],
        ["id"],
    )
    op.drop_column("shelduled_tasks", "shelduled_to")
    op.drop_column("shelduled_tasks", "task_sheldule")
    op.add_column("task_sheldules", sa.Column("schedule", sa.JSON(), nullable=False))
    op.drop_column("task_sheldules", "sheldule")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "task_sheldules",
        sa.Column(
            "sheldule",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("task_sheldules", "schedule")
    op.add_column(
        "shelduled_tasks",
        sa.Column("task_sheldule", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "shelduled_tasks",
        sa.Column(
            "shelduled_to",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint(
        "fk_shelduled_tasks_task_sheldules_id_task_schedule",
        "shelduled_tasks",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_shelduled_tasks_task_sheldules_id_task_sheldule",
        "shelduled_tasks",
        "task_sheldules",
        ["task_sheldule"],
        ["id"],
    )
    op.drop_column("shelduled_tasks", "scheduled_to")
    op.drop_column("shelduled_tasks", "task_schedule")
    op.drop_constraint(
        "fk_completed_tasks_shelduled_tasks_id_scheduled_task",
        "completed_tasks",
        type_="foreignkey",
    )
    op.drop_column("completed_tasks", "scheduled_task")
    op.drop_table("completedtasks_users")
    op.drop_table("taskschedules_users")
    # ### end Alembic commands ###
