"""empty message

Revision ID: 3573d566b6f0
Revises: fc06769379e7
Create Date: 2021-11-12 16:37:18.473874

"""
from alembic import op
import sqlalchemy as sa
import ormar.fields.sqlalchemy_uuid


# revision identifiers, used by Alembic.
revision = '3573d566b6f0'
down_revision = 'fc06769379e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_completed_tasks_shelduled_tasks_id_scheduled_task', 'completed_tasks', type_='foreignkey')
    op.drop_constraint('fk_completed_tasks_tasks_id_task', 'completed_tasks', type_='foreignkey')
    op.create_foreign_key('fk_completed_tasks_shelduled_tasks_id_scheduled_task', 'completed_tasks', 'shelduled_tasks', ['scheduled_task'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_completed_tasks_tasks_id_task', 'completed_tasks', 'tasks', ['task'], ['id'], ondelete='CASCADE')
    op.drop_constraint('fk_shelduled_tasks_tasks_id_task', 'shelduled_tasks', type_='foreignkey')
    op.drop_constraint('fk_shelduled_tasks_task_sheldules_id_task_schedule', 'shelduled_tasks', type_='foreignkey')
    op.create_foreign_key('fk_shelduled_tasks_tasks_id_task', 'shelduled_tasks', 'tasks', ['task'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_shelduled_tasks_task_sheldules_id_task_schedule', 'shelduled_tasks', 'task_sheldules', ['task_schedule'], ['id'], ondelete='CASCADE')
    op.drop_constraint('fk_task_sheldules_tasks_id_task', 'task_sheldules', type_='foreignkey')
    op.create_foreign_key('fk_task_sheldules_tasks_id_task', 'task_sheldules', 'tasks', ['task'], ['id'], ondelete='CASCADE')
    op.drop_column('task_sheldules', 'is_deleted')
    op.add_column('tasks', sa.Column('is_archived', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.drop_constraint('fk_tasks_apartments_id_apartment', 'tasks', type_='foreignkey')
    op.create_foreign_key('fk_tasks_apartments_id_apartment', 'tasks', 'apartments', ['apartment'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_tasks_apartments_id_apartment', 'tasks', type_='foreignkey')
    op.create_foreign_key('fk_tasks_apartments_id_apartment', 'tasks', 'apartments', ['apartment'], ['id'])
    op.drop_column('tasks', 'is_archived')
    op.add_column('task_sheldules', sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_constraint('fk_task_sheldules_tasks_id_task', 'task_sheldules', type_='foreignkey')
    op.create_foreign_key('fk_task_sheldules_tasks_id_task', 'task_sheldules', 'tasks', ['task'], ['id'])
    op.drop_constraint('fk_shelduled_tasks_task_sheldules_id_task_schedule', 'shelduled_tasks', type_='foreignkey')
    op.drop_constraint('fk_shelduled_tasks_tasks_id_task', 'shelduled_tasks', type_='foreignkey')
    op.create_foreign_key('fk_shelduled_tasks_task_sheldules_id_task_schedule', 'shelduled_tasks', 'task_sheldules', ['task_schedule'], ['id'])
    op.create_foreign_key('fk_shelduled_tasks_tasks_id_task', 'shelduled_tasks', 'tasks', ['task'], ['id'])
    op.drop_constraint('fk_completed_tasks_tasks_id_task', 'completed_tasks', type_='foreignkey')
    op.drop_constraint('fk_completed_tasks_shelduled_tasks_id_scheduled_task', 'completed_tasks', type_='foreignkey')
    op.create_foreign_key('fk_completed_tasks_tasks_id_task', 'completed_tasks', 'tasks', ['task'], ['id'])
    op.create_foreign_key('fk_completed_tasks_shelduled_tasks_id_scheduled_task', 'completed_tasks', 'shelduled_tasks', ['scheduled_task'], ['id'])
    # ### end Alembic commands ###
