"""empty message

Revision ID: c020bbb9aed9
Revises: 092d9a6968f8
Create Date: 2021-10-02 22:37:14.345797

"""
from alembic import op
import sqlalchemy as sa
import ormar.fields.sqlalchemy_uuid


# revision identifiers, used by Alembic.
revision = 'c020bbb9aed9'
down_revision = '092d9a6968f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('color', sa.String(length=6), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'color')
    # ### end Alembic commands ###
