services:
  db:
    image: "postgres:14"
    restart: always
    environment:
      - POSTGRES_DB=cleaning_app
      - POSTGRES_USER=debug
      - POSTGRES_PASSWORD=debug
    ports:
      - "5432:5432"
  
  backend:
    build:
      context: ./
      dockerfile: ./docker/dev.dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./cleaning_app:/app
      - ./scripts/start.sh:/root/start.sh
      - ./pyproject.toml:/root/poetry/pyproject.toml
      - ./pyproject.toml:/root/poetry/poetry.lock
