name: Check linting

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]


jobs:
  Run-Pre-Commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 32

      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      -
        name: Install pre-commit
        run: pip3 install pre-commit

      -
        name: Pre-commit
        run: pre-commit run --source ${{ github.event.before }} --origin ${{ github.event.after }}
