name: Check linting

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]


jobs:
  Run-Pre-Commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 32

      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      -
        name: Install pre-commit
        run: pip3 install pre-commit

      -
        name: Chech event_name
        run: echo ${{ github.event_name }}

      -
        name: Pre-commit (Push)
        if: ${{ github.event_name == 'push' }}
        run: pre-commit run --source ${{ github.event.before }} --origin ${{ github.event.after }}

      -
        name: Pre-commit (Pull-Request)
        if: ${{ github.event_name == 'pull_request' }}
        run: pre-commit run --source ${{ github.event.pull_request.base.sha }} --origin ${{ github.event.after }}
